### ISSUE TITLE
Cannot delete patient records on playground

### ISSUE THREAD

**Issue by buske** [phenotips/phenotips.org#12]
The `delete` button does not appear, and executing the delete action redirects me to a login page.

**Comment by sdumitriu** [comment]
That's done on purpose, normally guests shouldn't have the right to even view patient records in a real PhenoTips instance. Giving them edit rights is already almost a hack. Do you think it's useful to actually allow deleting?

**Comment by buske** [comment]
Hmm, no, not in terms of the permissions structure that is used to implement the guest functionality in the playground. But in terms of the playground's purpose and functionality, I see no reason to not allow people to delete records that they create. It sounds like it's not worth the effort to implement though.

**Comment by sdumitriu** [comment]
Since all anonymous users are anonymous, you can't just let users delete the records that __they__ created. This would mean that anybody can delete any guest-owned record.

**Comment by buske** [comment]
That depends on whether the xwiki implementation of `guest` considers all guests to be the same or not. Usually frameworks have cookie/ip-based differentiation, so theoretically we could do this, though I agree it's probably not worth it.

I actually think it makes more sense to allow anybody to delete any guest-owned record. Anybody can already edit any guest-owned record. Why is deleting different from editing?
